theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/logo-white.svg'
    footer: '/assets/images/logo-white.svg'
  home:
    head:
      title: site
  pages:
    index:
      truncate_description: 0
  posts:
    index:
      layout: list
    single:
      options:
        reading_time: false
        signature: true
        updated_at: false
  components:
    lightbox:
      disabled: false
      in_hero:
        disabled: true
      in_gallery:
        disabled: false
  image_sizes:
    _default:
      layouts:
        carousel:
          mobile:   360
          tablet:   555
          desktop:  800
    sections:
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1920
      pages:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1920
        item:
          mobile:   350
          tablet:   990
          desktop:  600
        layouts:
          list:
            mobile:   400
            tablet:   800
            desktop:  400