theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/logo-white.svg'
    footer: '/assets/images/logo-white.svg'
  home:
    head:
      title: site
  posts:
    index:
      layout: list
    single:
      options:
        reading_time: false
        signature: true
        updated_at: false
  components:
    lightbox:
      disabled: false
      in_hero:
        disabled: true
      in_gallery:
        disabled: false
