[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/lassociation/notre-equipe/index.html"
to = "/equipe/"

[[redirects]]
from = "/lassociation/notre-manifeste/index.html"
to = "/manifeste/"

[[redirects]]
from = "/newsletter/index.html"
to = "/publications/newsletter/"

[[redirects]]
from = "/actualites/2026-05-07-ma-commune-a-50c/index.html"
to = "/publications/2026-05-07-ma-commune-a-50c/"

[[redirects]]
from = "/actualites/index.html"
to = "/publications/"

[[redirects]]
from = "/fichiers/2026/index.html"
to = "/fichiers/2026/adapt-rapport-ma-commune-a-50-c-v4pdf/"

[[redirects]]
from = "/notre-equipe/index.html"
to = "/equipe/"

[[redirects]]
from = "/notre-manifeste/index.html"
to = "/manifeste/"

[[redirects]]
from = "/publications/2026-ma-commune-a-50c/index.html"
to = "/publications/2026-05-07-ma-commune-a-50c/"

